### ISSUE TITLE
Non-matlab code for DDIS?

### ISSUE THREAD

**Issue by xmba15** [roimehrez/DDIS#1]
Hi, as matlab codes only make it difficult for people who cannot purchase a matlab license or have no experience with matlab programming, I am wondering if you can publish a non-matlab version  for DDIS?

**Comment by ianni67** [comment]
I second this request. Matlab is both expensive and unsuitable for actually using the published software and thus reduces the potential users who would also cite the related paper.

**Comment by roimehrez** [comment]
It should be easy to reimplement.
Checkout my new repoasatory with similar idea in python.

בתאריך יום ג׳, 27 במרץ 2018, 10:36, מאת ianni67 ‏<notifications@github.com>:

**Comment by russkel** [comment]
@roimehrez sorry, which repository do you mean?

**Comment by roimehrez** [comment]
https://github.com/roimehrez/contextualLoss

בתאריך יום ו׳, 20 באפר׳ 2018, 4:10, מאת Russ ‏<notifications@github.com>:

**Comment by russkel** [comment]
Thanks @roimehrez
